tap "dart-lang/dart"
tap "homebrew/bundle"
tap "homebrew/core"
brew "cocoapods"
brew "fish"
brew "usbmuxd", args: ["HEAD"]
brew "libimobiledevice", args: ["HEAD"]
brew "ideviceinstaller"
brew "ios-deploy"
brew "node"
brew "watchman"
brew "yarn"
brew "dart-lang/dart/dart"
brew "talal/tap/bonclay"
cask install "iterm2"
cask install "visual-studio-code"